# Generated by Django 3.2 on 2022-06-25 17:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailNotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("advertisement", "advertisement email"),
                            ("personal", "personal email"),
                        ],
                        max_length=100,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("template_data", models.TextField()),
            ],
            options={
                "db_table": "notification_template",
            },
        ),
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "data",
                    models.JSONField(
                        verbose_name="store data in json, transmit into template"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cancelled", "notification cancelled"),
                            ("pending", "waiting to send"),
                            ("sent", "notification sent"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
                (
                    "is_advertisement",
                    models.BooleanField(
                        default=False,
                        verbose_name="Is ad or not. User can disable ad emails.",
                    ),
                ),
                ("type", models.CharField(default="email", max_length=100)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_notifications",
                        to="notifications.emailnotificationtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "email_notification",
            },
        ),
    ]
