# Generated by Django 3.2 on 2022-06-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailnotification",
            name="subject",
            field=models.TextField(default="", verbose_name="Email subject"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailnotification",
            name="title",
            field=models.TextField(default="", verbose_name="Email Title"),
            preserve_default=False,
        ),
    ]
