"""added unique constrain email field

Revision ID: 6f36c3a8d81f
Revises: 3dc6a23dac56
Create Date: 2022-07-25 16:54:01.798972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f36c3a8d81f'
down_revision = '3dc6a23dac56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
