# Generated by Django 3.2 on 2022-07-18 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='code',
        ),
        migrations.AddField(
            model_name='transaction',
            name='idempotence_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
