# Generated by Django 3.2 on 2022-07-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='plan_id',
            new_name='plan',
        ),
    ]
