# Generated by Django 3.2 on 2022-07-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_change_code_field_to_idempotence_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Optional', 'Optional')], default='Basic', max_length=30),
        ),
    ]
